### ISSUE TITLE
Build error dop251/goja/parser

### ISSUE THREAD

**Issue by jordantrizz** [mostafa/goja_debugger#6]
Getting the following build error

```
go: finding github.com/dop251/goja latest
build github.com/dop251/goja: cannot load github.com/dop251/goja/parser: module github.com/dop251/goja@latest found (v0.0.0-20220516123900-4418d4575a41, replaced by ../goja), but does not contain package github.com/dop251/goja/parser
```

**Comment by mostafa** [comment]
@jordantrizz
I forgot to mention this in the README, but I will after this.
https://github.com/mostafa/goja_debugger/blob/3e295b275cb1afb9959bcc3cf13b3736c37fa932/go.mod#L12
Due to the line above, you need to also clone [Goja](https://github.com/mostafa/goja) into the same directory as `goja_debugger` and check out the `debugger` branch.
```bash
git clone https://github.com/mostafa/goja
cd goja
git checkout debugger
cd ..
git clone https://github.com/mostafa/goja_debugger
cd goja_debugger
go build
```
